"""Authenticated standalone checklist interface."""
PAGE = r'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Centro de Desarrollo · Traccar Manager</title>
<style>
:root{font-family:system-ui,-apple-system,sans-serif;color-scheme:dark}body{margin:0;background:#0a1220;color:#e8f2ff}main{max-width:1100px;margin:auto;padding:22px}a{color:#71d8ef}header{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}h1{font-size:clamp(22px,4vw,32px);margin:12px 0}p{color:#aabbd2}.card{background:#142238;border:1px solid #30445f;border-radius:13px;padding:16px;margin:13px 0}input,select,textarea,button{font:inherit;color:#e8f2ff;background:#0c1829;border:1px solid #415875;border-radius:8px;padding:9px}button{cursor:pointer;background:#163e53}button:hover{background:#24546b}.filters{display:flex;gap:10px;flex-wrap:wrap}.filters input{flex:1;min-width:180px}.task{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;border-bottom:1px solid #30445f;padding:13px 0}.task:last-child{border-bottom:0}.task small{color:#a9bed5}.task strong{display:block}.pill{font-size:12px;padding:4px 8px;border:1px solid #45627a;border-radius:15px}.task button{min-width:82px}dialog{max-width:min(650px,94vw);width:100%;border:1px solid #49617c;border-radius:15px;background:#101c2f;color:#edf5ff}dialog::backdrop{background:#000a}dialog label{display:block;margin-top:12px}dialog select,dialog textarea{width:100%;box-sizing:border-box}textarea{min-height:90px}#message{min-height:22px}progress{width:100%;height:16px;accent-color:#57d4a4}@media(max-width:550px){.task{grid-template-columns:1fr}.filters>*{width:100%}}
</style></head><body><main><header><div><small>TRACCAR MANAGER · SUPERADMINISTRADOR</small><h1>Centro de Desarrollo y Progreso</h1></div><a href="/manager/">← Volver al panel</a></header>
<p>Checklist oficial del proyecto. Solo las tareas verificadas con documentación y evidencias cuentan como completadas.</p>
<section class="card"><strong id="summary">Cargando avances…</strong><progress id="bar" max="100" value="0"></progress><p id="message" role="status"></p></section>
<section class="card"><div class="filters"><input id="search" type="search" placeholder="Buscar tarea o identificador"><select id="state-filter"><option value="">Todos los estados</option><option value="pending">Pendiente</option><option value="in_development">En desarrollo</option><option value="in_testing">En pruebas</option><option value="blocked">Bloqueado</option><option value="verified">Verificado</option></select></div><div id="tasks"></div></section>
<dialog id="editor"><form id="edit-form"><h2 id="edit-title">Editar tarea</h2><p id="edit-id"></p><label>Estado<select id="edit-state"><option value="pending">Pendiente</option><option value="in_development">En desarrollo</option><option value="in_testing">En pruebas</option><option value="blocked">Bloqueado</option><option value="verified">Verificado</option></select></label><label>Documentación<select id="edit-doc"><option value="pending">Pendiente</option><option value="in_review">En revisión</option><option value="verified">Verificada</option><option value="not_applicable">No aplica (justificado)</option></select></label><label>Evidencias verificables (una referencia por línea)<textarea id="edit-evidence" maxlength="10500" placeholder="Commit, prueba, documento, justificación…"></textarea></label><p id="edit-error" role="alert"></p><button type="submit">Guardar cambio</button> <button type="button" id="cancel">Cancelar</button></form></dialog></main>
<script>
"use strict";
let tasks=[],selected=null;
const $=id=>document.getElementById(id);
const labels={pending:"Pendiente",in_development:"En desarrollo",in_testing:"En pruebas",blocked:"Bloqueado",verified:"Verificado"};
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function render(){const root=$("tasks");root.replaceChildren();const q=$("search").value.toLowerCase(),f=$("state-filter").value;let shown=0,group="";
for(const t of tasks){if(f&&t.state!==f)continue;if(q&&!((t.task_id+" "+t.title+" "+t.phase).toLowerCase().includes(q)))continue;
if(group!==t.phase){group=t.phase;root.append(node("h2",group))}
const row=node("div",undefined,"task"),info=node("div");info.append(node("strong",t.task_id+" · "+t.title),node("small",labels[t.state]+" · Documentación: "+t.doc_state+" · "+t.evidence.length+" evidencias"));const b=node("button","Editar");b.type="button";b.addEventListener("click",()=>edit(t));row.append(info,b);root.append(row);shown++}
if(!shown)root.append(node("p","No hay tareas con esos filtros."))}
function setData(data){tasks=data.tasks;$("summary").textContent=data.verified+" de "+data.total+" tareas verificadas · "+(data.percentage??"—")+"%";$("bar").value=data.percentage||0;render()}
async function load(){try{const r=await fetch("/manager/api/progress",{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw Error("Acceso denegado o servicio no disponible ("+r.status+")");setData(await r.json())}catch(e){$("message").textContent=e.message}}
function edit(t){selected=t;$("edit-title").textContent=t.title;$("edit-id").textContent=t.task_id;$("edit-state").value=t.state;$("edit-doc").value=t.doc_state;$("edit-evidence").value=t.evidence.join("\n");$("edit-error").textContent="";$("editor").showModal()}
$("cancel").onclick=()=>$("editor").close();$("search").oninput=render;$("state-filter").onchange=render;
$("edit-form").onsubmit=async e=>{e.preventDefault();if(!selected)return;const payload={task_id:selected.task_id,state:$("edit-state").value,doc_state:$("edit-doc").value,evidence:$("edit-evidence").value.split("\n").map(s=>s.trim()).filter(Boolean)};
try{const r=await fetch("/manager/api/progress",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-Requested-With":"TraccarManager"} ,body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo guardar");setData(data);$("editor").close();$("message").textContent="Cambio guardado con auditoría."}catch(err){$("edit-error").textContent=err.message}};
load();
</script></body></html>'''
