import { chromium } from '../../.visual-test/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const sizes=[{name:'mobile',width:390,height:844},{name:'tablet',width:768,height:1024},{name:'desktop',width:1366,height:900}];
for(const size of sizes){
const page=await browser.newPage({viewport:{width:size.width,height:size.height},deviceScaleFactor:1});
await page.clock.install();
let inventoryMode='normal';
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**', async route=>{
 const u=new URL(route.request().url());const path=u.pathname;
 const respond=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
 if(path.endsWith('/auth/me'))return respond({authenticated:true,username:'visual-fixture'});
 if(path.endsWith('/dashboard/snapshot'))return respond({schema_version:1,request_id:u.searchParams.get('request_id'),general:{traccar_service:Object.fromEntries(['state','substate','load_state','unit_file_state','result'].map(k=>[k,{availability:'PENDING_PROVIDER'}]))}});
 if(path.endsWith('/devices/inventory')&&inventoryMode==='unavailable')return respond({error:'fixture_inventory_unavailable'},503);
 if(path.endsWith('/devices/inventory')&&inventoryMode==='many')return respond({privacy:{unique_id_exposed:false,phone_exposed:false,position_exposed:false,coordinates_exposed:false},devices:Array.from({length:12},(_,i)=>({name:'Unidad de prueba '+(i+1),company:'Empresa de prueba',category:'truck',state:i<8?'STALE':'INACTIVE',enabled:true,last_report_age_seconds:i<8?90000:5000}))});
 if(path.endsWith('/devices/inventory')&&inventoryMode==='no-attention')return respond({privacy:{unique_id_exposed:false,phone_exposed:false,position_exposed:false,coordinates_exposed:false},devices:[{name:'Vehículo de demostración',company:'Empresa de prueba',category:'automobile',state:'ONLINE',enabled:true,last_report_age_seconds:120}]});
 if(path.endsWith('/devices/inventory'))return respond({privacy:{unique_id_exposed:false,phone_exposed:false,position_exposed:false,coordinates_exposed:false},devices:[{name:'Vehículo de demostración',company:'Empresa de prueba',category:'automobile',state:'ONLINE',enabled:true,last_report_age_seconds:120},{name:'Camión de demostración',company:'Empresa de prueba',category:'truck',state:'STALE',enabled:true,last_report_age_seconds:90000}]});
 return respond({error:'fixture_unavailable'},503);
});
await page.goto('https://homecargps.com/manager/',{waitUntil:'domcontentloaded',timeout:15000});
await page.waitForTimeout(2000);
assert.match(await page.locator('body').getAttribute('class')||'',/authenticated/);
assert.equal(await page.locator('#inventory-search').getAttribute('placeholder'),'Buscar por nombre o empresa');
assert.match(await page.locator('#inventory-search').getAttribute('aria-label'),/nombre de dispositivo o empresa/);
console.log('AUTHENTICATED OK');
const accessibilityReferences=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);const duplicates=ids.filter((id,i)=>ids.indexOf(id)!==i);const missing=[];for(const el of document.querySelectorAll('[aria-labelledby],[aria-describedby],label[for]')){for(const attr of ['aria-labelledby','aria-describedby','for']){const value=el.getAttribute(attr);if(!value)continue;for(const id of value.trim().split(/\s+/)){if(!document.getElementById(id))missing.push(attr+':'+id);}}}return {duplicates,missing};});
assert.deepEqual(accessibilityReferences.duplicates,[]);
assert.deepEqual(accessibilityReferences.missing,[]);
console.log(size.name,'ACCESSIBILITY ID AND REFERENCE INTEGRITY OK');
assert.equal(await page.locator('.device-row').count(),1);
console.log('INITIAL ATTENTION FILTER OK');
assert.equal(await page.locator('#fleet-summary-total').innerText(),'2');
assert.equal(await page.locator('#fleet-online').innerText(),'1');
assert.equal(await page.locator('#fleet-attention').innerText(),'1');
assert.equal(await page.locator('#fleet-other').innerText(),'0');
console.log(size.name,'DASHBOARD FLEET COUNTS OK');
assert.equal(await page.locator('#diagnostic-center').getAttribute('aria-labelledby'),'diagnostic-title');
assert.equal(await page.locator('#preventive-diagnostics').getAttribute('aria-labelledby'),'preventive-diagnostics-title');
assert.equal(await page.locator('#diagnostic-title').count(),1);
assert.equal(await page.locator('#preventive-diagnostics-title').count(),1);
console.log(size.name,'UNIQUE DIAGNOSTIC HEADINGS OK');
assert.match(await page.locator('#fleet-last-updated').innerText(),/Actualizado:/);
assert.match(await page.locator('#fleet-freshness').innerText(),/Datos recientes/);
assert.equal(await page.locator('#fleet-priority-export-warning').isHidden(),true);
assert.match(await page.locator('#fleet-priority-context').innerText(),/No representan seguimiento GPS en tiempo real/);
await page.clock.fastForward(16*60*1000);
assert.match(await page.locator('#fleet-freshness').innerText(),/Datos desactualizados/);
assert.match(await page.locator('#fleet-priority-export-warning').innerText(),/Actualiza antes de exportar/);
assert.match(await page.locator('#fleet-priority-context').innerText(),/Actualiza el inventario antes de tomar decisiones/);
assert.match(await page.locator('#fleet-priority-context').getAttribute('class'),/stale/);
assert.equal(await page.locator('#fleet-priority-export').isDisabled(),true);
console.log(size.name,'FLEET STALE DATA WARNING OK');
await page.locator('#fleet-refresh').click({force:true});
await page.waitForFunction(()=>document.querySelector('#fleet-refresh').disabled===false);
assert.equal(await page.locator('#fleet-summary-total').innerText(),'2');
assert.match(await page.locator('#fleet-last-updated').innerText(),/Actualizado:/);
assert.match(await page.locator('#fleet-freshness').innerText(),/Datos recientes/);
console.log(size.name,'FLEET MANUAL REFRESH WITHOUT RELOAD OK');
assert.equal(await page.locator('.fleet-priority-row').count(),1);
assert.match(await page.locator('#fleet-priority-list').innerText(),/Camión de demostración/);
assert.match(await page.locator('#fleet-priority-count').innerText(),/1 por revisar/);
assert.equal(await page.locator('#fleet-priority-critical').innerText(),'Críticas: 1');
assert.equal(await page.locator('#fleet-priority-preventive').innerText(),'Preventivas: 0');
assert.match(await page.locator('#fleet-priority-visible-count').innerText(),/Mostrando 1 de 1 dispositivos pendientes/);
console.log(size.name,'FLEET PRIORITY VISIBLE OK');
assert.equal(await page.locator('#fleet-priority-export').isDisabled(),false);
const exportDownload=page.waitForEvent('download');
await page.locator('#fleet-priority-export').click({force:true});
const exportFile=await exportDownload;
assert.equal(exportFile.suggestedFilename(),'prioridades-flota.csv');
const fs=await import('node:fs/promises');
const exportedCsv=await fs.readFile(await exportFile.path(),'utf8');
assert.match(exportedCsv,/Camión de demostración/);
assert.match(exportedCsv,/Inventario consultado/);
assert.match(exportedCsv,/Vigencia del inventario/);
assert.match(exportedCsv,/Datos recientes/);
assert.doesNotMatch(exportedCsv,/Datos desactualizados/);
assert.match(exportedCsv,/\(Lima\)/);
assert.match(exportedCsv,/\d{1,2}\/\d{1,2}\/\d{2,4}/);
assert.doesNotMatch(exportedCsv,/Sin consulta confirmada/);
assert.doesNotMatch(exportedCsv,/Vehículo de demostración|Empresa de prueba|unique_id|coordinates|phone/);
console.log(size.name,'PRIORITY CSV EXPORT PRIVACY OK');
await page.clock.fastForward(16*60*1000);
assert.equal(await page.locator('.device-row').first().getAttribute('aria-disabled'),'true');
await page.locator('.device-row').first().evaluate(el=>el.click());
assert.equal(await page.locator('#device-detail-modal').getAttribute('aria-hidden'),'true');
assert.equal(await page.locator('.fleet-priority-open').first().isDisabled(),true);
await page.locator('.fleet-priority-open').first().evaluate(el=>el.click());
assert.equal(await page.locator('#device-detail-modal').getAttribute('aria-hidden'),'true');
assert.match(await page.locator('#fleet-freshness').innerText(),/Datos desactualizados/);
assert.equal(await page.locator('#fleet-priority-export').isDisabled(),true);
await page.locator('#fleet-priority-refresh').click({force:true});
await page.waitForFunction(()=>document.querySelector('#fleet-freshness')?.textContent==='Datos recientes');
assert.equal(await page.locator('#fleet-priority-export-warning').isHidden(),true);
assert.equal(await page.locator('.fleet-priority-open').first().isDisabled(),false);
assert.equal(await page.locator('.device-row').first().getAttribute('aria-disabled'),'false');
console.log(size.name,'CSV STALE WARNING AND REFRESH OK');
await page.locator('[data-priority-filter=preventive]').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),0);
assert.match(await page.locator('#fleet-priority-list').innerText(),/No hay prioridades preventivas/);
assert.equal(await page.locator('#fleet-priority-export').isDisabled(),true);
assert.equal(await page.locator('#fleet-priority-critical').innerText(),'Críticas: 1');
await page.locator('[data-priority-filter=critical]').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),1);
assert.equal(await page.locator('[data-priority-filter=critical]').getAttribute('aria-pressed'),'true');
await page.locator('[data-priority-filter=all]').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),1);
console.log(size.name,'PRIORITY FILTERS AND COUNTERS OK');
await page.locator('#fleet-priority-search-input').fill('camión');
assert.equal(await page.locator('.fleet-priority-row').count(),1);
await page.locator('#fleet-priority-search-input').fill('sin coincidencia');
assert.equal(await page.locator('.fleet-priority-row').count(),0);
assert.match(await page.locator('#fleet-priority-list').innerText(),/No hay dispositivos que coincidan/);
assert.match(await page.locator('#fleet-priority-visible-count').innerText(),/Mostrando 0 de 1 dispositivos pendientes · 0 coinciden/);
assert.equal(await page.locator('#fleet-priority-critical').innerText(),'Críticas: 1');
await page.locator('[data-priority-filter=preventive]').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),0);
await page.locator('#fleet-priority-search-input').fill('');
await page.locator('[data-priority-filter=all]').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),1);
console.log(size.name,'PRIORITY NAME SEARCH COMBINED WITH FILTER OK');
assert.equal(await page.locator('#fleet-priority-clear').isDisabled(),true);
await page.locator('#fleet-priority-search-input').fill('sin coincidencia');
await page.locator('[data-priority-filter=preventive]').click({force:true});
assert.equal(await page.locator('#fleet-priority-clear').isDisabled(),false);
await page.locator('#fleet-priority-clear').click({force:true});
assert.equal(await page.locator('#fleet-priority-search-input').inputValue(),'');
assert.equal(await page.locator('[data-priority-filter=all]').getAttribute('aria-pressed'),'true');
assert.equal(await page.locator('#fleet-priority-clear').isDisabled(),true);
assert.equal(await page.locator('.fleet-priority-row').count(),1);
console.log(size.name,'CLEAR PRIORITY SEARCH AND FILTERS OK');
inventoryMode='many';
await page.locator('#fleet-priority-refresh').click({force:true});
await page.waitForFunction(()=>document.querySelector('#fleet-summary-total')?.textContent==='12');
assert.equal(await page.locator('.fleet-priority-row').count(),5);
assert.match(await page.locator('#fleet-priority-visible-count').innerText(),/Mostrando 5 de 12/);
await page.locator('.fleet-priority-more').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),10);
assert.match(await page.locator('#fleet-priority-visible-count').innerText(),/Mostrando 10 de 12/);
assert.equal(await page.locator('.fleet-priority-less').count(),1);
await page.locator('.fleet-priority-less').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),5);
assert.equal(await page.locator('.fleet-priority-less').count(),0);
assert.match(await page.locator('#fleet-priority-visible-count').innerText(),/Mostrando 5 de 12/);
assert.equal(await page.locator('#fleet-priority-search-input').evaluate(el=>el===document.activeElement),true);
await page.locator('.fleet-priority-more').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),10);
await page.locator('.fleet-priority-more').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),12);
const manyDownload=page.waitForEvent('download');
await page.locator('#fleet-priority-export').click({force:true});
const manyCsv=await fs.readFile(await (await manyDownload).path(),'utf8');
assert.equal((manyCsv.match(/Unidad de prueba/g)||[]).length,12);
assert.equal((manyCsv.match(/\(Lima\)/g)||[]).length,12);
assert.equal(await page.locator('.fleet-priority-more').count(),0);
assert.equal(await page.locator('.fleet-priority-less').count(),1);
await page.locator('[data-priority-filter=preventive]').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),4);
const filteredDownload=page.waitForEvent('download');
await page.locator('#fleet-priority-export').click({force:true});
const filteredCsv=await fs.readFile(await (await filteredDownload).path(),'utf8');
assert.equal((filteredCsv.match(/Unidad de prueba/g)||[]).length,4);
assert.doesNotMatch(filteredCsv,/Unidad de prueba 1"/);
assert.match(await page.locator('#fleet-priority-visible-count').innerText(),/Mostrando 4 de 12/);
await page.locator('[data-priority-filter=all]').click({force:true});
assert.equal(await page.locator('.fleet-priority-row').count(),5);
console.log(size.name,'EXPAND PRIORITIES IN BATCHES AND RESET ON FILTER OK');
inventoryMode='normal';
await page.locator('#fleet-priority-refresh').click({force:true});
await page.waitForFunction(()=>document.querySelector('#fleet-summary-total')?.textContent==='2');
await page.locator('#fleet-priority-refresh').click({force:true});
await page.waitForFunction(()=>document.querySelector('#fleet-priority-refresh').disabled===false);
assert.equal(await page.locator('.fleet-priority-row').count(),1);
assert.match(await page.locator('#fleet-priority-count').innerText(),/1 por revisar/);
assert.match(await page.locator('#fleet-last-updated').innerText(),/Actualizado:/);
console.log(size.name,'PRIORITIES REFRESH IN PLACE OK');
const priorityButton=page.locator('.fleet-priority-open').first();
await priorityButton.click({force:true});
assert.equal(await page.locator('#device-detail-modal').getAttribute('aria-hidden'),'false');
assert.equal(await page.locator('#device-detail-close').isVisible(),true);
assert.match(await page.locator('#device-detail-body').innerText(),/Protegido por privacidad/);
assert.match(await page.locator('#device-detail-body').innerText(),/Atención prioritaria/);
assert.match(await page.locator('.diag-guidance').innerText(),/Prioridad alta/);
assert.equal(await page.locator('.diag-guidance li').count(),3);
assert.match(await page.locator('.diag-guidance').innerText(),/no confirma la causa raíz/);
console.log(size.name,'DIAGNOSTIC SEVERITY AND SAFE GUIDANCE OK');
await page.locator('#device-detail-close').click({force:true});
assert.equal(await page.locator('#device-detail-modal').getAttribute('aria-hidden'),'true');
assert.equal(await page.locator('#dashboard-overview').isVisible(),true);
assert.equal(await priorityButton.evaluate(el=>el===document.activeElement),true);
assert.equal(await page.locator('[data-section=summary]').first().getAttribute('aria-current'),'page');
console.log(size.name,'PRIORITY DETAIL RETURNS TO DASHBOARD AND FOCUS OK');
assert.equal(await page.locator('#inventory-filter').inputValue(),'ATTENTION');
await page.locator('[data-section=devices]').first().evaluate(el=>el.click());
await page.waitForTimeout(200);
await page.locator('#inventory-filter').evaluate(el=>{el.value='ALL';el.dispatchEvent(new Event('change',{bubbles:true}));});
await page.locator('#inventory-search').fill('Camión');
assert.equal(await page.locator('.device-row').count(),1);
console.log('SEARCH ALL OK');
await page.locator('#inventory-filter').evaluate(el=>{el.value='ATTENTION';el.dispatchEvent(new Event('change',{bubbles:true}));});
assert.equal(await page.locator('.device-row').count(),1);
console.log('SEARCH ATTENTION OK');
const chip=page.locator('.device-row .device-state').first();
assert.match(await chip.innerText(),/Sin reporte/);
const chipStyle=await chip.evaluate(el=>({radius:getComputedStyle(el).borderRadius,bg:getComputedStyle(el).backgroundColor,display:getComputedStyle(el).display}));
assert.ok(['flex','inline-flex'].includes(chipStyle.display));
assert.equal(chipStyle.radius,'999px');
console.log(size.name,'STATUS CHIP STYLED OK');
const artwork=await page.locator('.device-row .vehicle-type-image').first().evaluate(el=>({loaded:el.complete&&el.naturalWidth>0,width:getComputedStyle(el).width,height:getComputedStyle(el).height,fit:getComputedStyle(el).objectFit}));
assert.equal(artwork.loaded,true,`${size.name}: vehicle artwork failed to load`);
assert.equal(artwork.width,'64px');
assert.equal(artwork.height,'43px');
assert.equal(artwork.fit,'contain');
console.log(size.name,'VEHICLE ARTWORK OK');
await page.locator('#inventory-search').fill('Vehículo');
assert.equal(await page.locator('.device-row').count(),0);
console.log('FILTER EXCLUDES ONLINE OK');
assert.match(await page.locator('.inventory-empty').textContent(),/Sin coincidencias/);
assert.match(await page.locator('.inventory-empty').textContent(),/cambia el filtro/);
console.log(size.name,'EMPTY SEARCH EXPLAINED OK');
await page.locator('#inventory-search').evaluate(el=>{el.value='';el.dispatchEvent(new Event('input',{bubbles:true}));});
await page.locator('#inventory-filter').selectOption('ONLINE');
assert.equal(await page.locator('.device-row').count(),1);
await page.locator('#inventory-filter').evaluate(el=>{el.value='ATTENTION';el.dispatchEvent(new Event('change',{bubbles:true}));});
await page.locator('#inventory-search').evaluate(el=>{el.value='';el.dispatchEvent(new Event('input',{bubbles:true}));});
await page.locator('#inventory-search').evaluate(el=>{el.value='';el.dispatchEvent(new Event('input',{bubbles:true}));});
await page.locator('.device-row').first().click();
assert.equal(await page.locator('#device-detail-modal').getAttribute('aria-hidden'),'false');
console.log(size.name,'DETAIL OPEN OK');
assert.equal(await page.locator('#device-detail-close').evaluate(el=>el===document.activeElement),true);
await page.keyboard.press('Escape');
assert.equal(await page.locator('#device-detail-modal').getAttribute('aria-hidden'),'true');
assert.equal(await page.locator('.device-row').first().evaluate(el=>el===document.activeElement),true);
console.log(size.name,'ESCAPE AND FOCUS RESTORE OK');
await page.locator('.device-row').first().click();
assert.match(await page.locator('#device-detail-body').innerText(),/Protegido por privacidad/);
console.log('PRIVACY OK');

assert.deepEqual(errors,[]);
console.log(size.name,'NO JS ERRORS');
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);
assert.equal(overflow,false,`${size.name}: unexpected horizontal page overflow`);
console.log(size.name,'NO HORIZONTAL OVERFLOW');
const shot=(process.env.SCREENSHOT_PATH||'/tmp/manager-devices-fixture.png').replace(/\.png$/,`-${size.name}.png`);
await page.screenshot({path:shot,fullPage:true});
console.log(size.name,'SCREENSHOT',shot);
inventoryMode='no-attention';
await page.reload({waitUntil:'domcontentloaded'});
await page.locator('.inventory-empty').waitFor({state:'attached',timeout:8000});
assert.match(await page.locator('.inventory-empty').textContent(),/Sin dispositivos que requieran atención/);
assert.equal(await page.locator('#inventory-count').innerText(),'0 de 1');
console.log(size.name,'NO ATTENTION EMPTY STATE OK');
assert.equal(await page.locator('#fleet-summary-total').innerText(),'1');
assert.equal(await page.locator('#fleet-attention').innerText(),'0');
console.log(size.name,'DASHBOARD CLEAR STATE OK');
assert.equal(await page.locator('.fleet-priority-row').count(),0);
assert.match(await page.locator('#fleet-priority-list').textContent(),/Sin dispositivos inactivos/);
assert.equal(await page.locator('#fleet-priority-critical').innerText(),'Críticas: 0');
assert.equal(await page.locator('#fleet-priority-preventive').innerText(),'Preventivas: 0');
console.log(size.name,'FLEET PRIORITY CLEAR OK');
inventoryMode='unavailable';
await page.reload({waitUntil:'domcontentloaded'});
await page.locator('.inventory-unavailable').waitFor({state:'attached',timeout:8000});
assert.match(await page.locator('.inventory-unavailable').textContent(),/No se pudo cargar el inventario/);
assert.equal(await page.locator('#inventory-count').innerText(),'No disponible');
assert.deepEqual(errors,[]);
assert.match(await page.locator('.inventory-unavailable').textContent(),/Actualizar inventario/);
console.log(size.name,'INVENTORY FAILURE MESSAGE OK');
assert.equal(await page.locator('#fleet-summary-total').innerText(),'—');
assert.match(await page.locator('#fleet-summary-note').textContent(),/temporalmente no disponible/);
console.log(size.name,'DASHBOARD UNAVAILABLE STATE OK');
assert.match(await page.locator('#fleet-last-updated').innerText(),/Error al actualizar/);
assert.equal(await page.locator('#fleet-refresh').isDisabled(),false);
assert.match(await page.locator('#fleet-freshness').innerText(),/Sin datos confirmados/);
assert.match(await page.locator('#fleet-priority-context').innerText(),/No hay inventario confirmado/);
assert.equal(await page.locator('#fleet-priority-refresh').isDisabled(),false);
console.log(size.name,'FLEET REFRESH ERROR STATE OK');
assert.match(await page.locator('#fleet-priority-count').innerText(),/No disponible/);
assert.equal(await page.locator('.fleet-priority-row').count(),0);
assert.equal(await page.locator('#fleet-priority-critical').innerText(),'Críticas: —');
assert.equal(await page.locator('#fleet-priority-preventive').innerText(),'Preventivas: —');
assert.match(await page.locator('#fleet-priority-visible-count').innerText(),/No hay resultados confirmados/);
assert.equal(await page.locator('#fleet-priority-export').isDisabled(),true);
console.log(size.name,'FLEET PRIORITY UNAVAILABLE OK');
await page.locator('#inventory-search').evaluate(el=>{el.value='dispositivo';el.dispatchEvent(new Event('input',{bubbles:true}));});
await page.locator('#inventory-filter').evaluate(el=>{el.value='ALL';el.dispatchEvent(new Event('change',{bubbles:true}));});
assert.equal(await page.locator('.inventory-unavailable').count(),1);
assert.equal(await page.locator('#inventory-count').innerText(),'No disponible');
assert.equal(await page.locator('.device-row').count(),0);
console.log(size.name,'FAILED INVENTORY CANNOT REAPPEAR THROUGH FILTERS OK');
await page.locator('#inventory-search').evaluate(el=>{el.value='';el.dispatchEvent(new Event('input',{bubbles:true}));});
await page.locator('#inventory-filter').evaluate(el=>{el.value='ATTENTION';el.dispatchEvent(new Event('change',{bubbles:true}));});
inventoryMode='normal';
await page.locator('[data-section=devices]').first().evaluate(el=>el.click());
await page.locator('.inventory-retry').click();
await page.waitForFunction(()=>document.querySelector('#inventory-count')?.textContent==='1 de 2',{timeout:8000});
assert.equal(await page.locator('.inventory-unavailable').count(),0);
console.log(size.name,'RETRY RECOVERS INVENTORY OK');
let refreshRequests=0;
let releaseRefresh;
const refreshGate=new Promise(resolve=>{releaseRefresh=resolve;});
await page.route('**/api/devices/inventory',async route=>{refreshRequests++;await refreshGate;await route.fallback();});
await page.locator('#inventory-refresh').click();
await page.waitForFunction(()=>document.querySelector('#inventory-refresh')?.disabled===true);
assert.equal(await page.locator('#inventory-refresh').innerText(),'Actualizando…');
assert.equal(await page.locator('#fleet-refresh').isDisabled(),true);
assert.equal(await page.locator('#fleet-priority-refresh').isDisabled(),true);
await page.locator('#inventory-refresh').evaluate(el=>el.click());
assert.equal(refreshRequests,1);
releaseRefresh();
await page.waitForFunction(()=>document.querySelector('#inventory-refresh')?.disabled===false);
assert.equal(refreshRequests,1);
assert.match(await page.locator('#inventory-refresh').innerText(),/Actualizar inventario/);
await page.unroute('**/api/devices/inventory');
console.log(size.name,'INVENTORY REFRESH SINGLE REQUEST AND BUTTON STATES OK');
inventoryMode='unavailable';
await page.locator('#inventory-refresh').click();
await page.locator('.inventory-unavailable').waitFor({state:'attached',timeout:8000});
assert.equal(await page.locator('#inventory-refresh').isDisabled(),false);
assert.match(await page.locator('#inventory-refresh').innerText(),/Actualizar inventario/);
assert.equal(await page.locator('#inventory-count').innerText(),'No disponible');
assert.equal(await page.locator('#fleet-priority-export').isDisabled(),true);
inventoryMode='normal';
await page.locator('#inventory-refresh').click();
await page.waitForFunction(()=>document.querySelector('#inventory-count')?.textContent==='1 de 2',{timeout:8000});
assert.equal(await page.locator('.inventory-unavailable').count(),0);
assert.equal(await page.locator('#inventory-refresh').isDisabled(),false);
console.log(size.name,'INVENTORY REFRESH NETWORK FAILURE AND RECOVERY OK');
assert.equal(await page.locator('#fleet-summary-total').innerText(),'2');
assert.equal(await page.locator('#fleet-attention').innerText(),'1');
console.log(size.name,'DASHBOARD RECOVERY OK');
assert.equal(await page.locator('.fleet-priority-row').count(),1);
console.log(size.name,'FLEET PRIORITY RECOVERED OK');
await page.close();
}
await browser.close();
